In [1]:
import numpy as np

In [10]:
a = np.array([1,2,3]) # numpy array: grid of values indexed by a tuple
print(a)
print(a.shape) # denotes size and dimension as a tuple
print(a[0], a[1], a[2])
a[0] = 5
print(a)

b = np.array([[1,2,3],[4,5,6]]) # 2d array
print(b)
print(b.shape)
print(b[0,0]) # retrieve specific element

c = np.array([1.0, 1.1, 1.2]) # floats
print(c)

[1 2 3]
(3,)
1 2 3
[5 2 3]
[[1 2 3]
 [4 5 6]]
(2, 3)
1
[1.  1.1 1.2]


In [17]:
a = np.zeros((2,3)) # create an array filled with zeros; parameters are array dimensions
print(a)

b = np.ones((1,2)) # create array filled with ones
print(b)

c = np.full((2,3), 7) # create array filled with user specified values
print(c)

d = np.zeros((5)) # one dimensional
print(d)

e = np.random.random((3,3)) # create array filled with random values
print(e)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]]
[[7 7 7]
 [7 7 7]]
[0. 0. 0. 0. 0.]
[[0.34946379 0.9734756  0.07905021]
 [0.86146167 0.27489176 0.91202167]
 [0.18396927 0.59702846 0.59060843]]


In [20]:
a = np.array([[1,2,3,4], [5,6,7,8],[9,10,11,12]])
print(a)

b = a[:2, 1:3] # slice first two rows and columns 1&2
print(b)

print(a[0,1]) # slice is a view into the data
b[0,0] = 75 # if you modify the slice
print(a[0,1]) # it modifies the original data
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3]
 [6 7]]
2
75
[[ 1 75  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [23]:
# boolean array values
a = np.array([[1,2],[3,4],[5,6]])
print(a)

print(a > 2)

print(a[a>2])

[[1 2]
 [3 4]
 [5 6]]
[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]


In [35]:
# basic math
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

print(x)
print(y)

print(x + y)
print(np.add(x,y))

print(x-y)
print(np.subtract(x,y))

print(x*y)
print(np.multiply(x,y))

print(x/y)
print(np.divide(x,y))

print(x**y)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[    1    64]
 [ 2187 65536]]


In [38]:
print(np.sum(x)) # sum of all values in x
print(np.sum(x, axis=0)) # sum of values in columns
print(np.sum(x, axis=1)) # sum of values in rows

10
[4 6]
[3 7]
